name: Pytest

on: [pull_request]

jobs:
  build:
      runs-on: ubuntu-latest
      env:
        DIGIKEY_INVENTREE_TEST_MODE: "True"
        DIGIKEY_INVENTREE_TEST_CONFIG_PATH: "tests/test_data/test_config.ini"
        CRYPTOGRAPHY_DONT_BUILD_RUST: "1"
      strategy:
        matrix:
          python-version: ["pypy3.8", "3.8", "pypy3.9", "pypy3.10", "3.9", "3.10", "3.11"]
  
      steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Pytest
        run: |
          pip install pytest pytest-cov
          python -m pytest --cov=src --cov-report=xml --cov-report=html --junitxml=junit/test-results.xml
