# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Publish python poetry package
      # You may pin to the exact commit or the version.
      # uses: JRubics/poetry-publish@b71e946be561eaf8bfb7562ecc97c26fb8583070
      uses: JRubics/poetry-publish@v1.17
      with:
        # The version of python to install
        python_version: 3.8 # optional, default is latest
        # The version of poetry to install
        poetry_version: 1.7.0 # optional, default is latest
        # API token to authenticate when uploading package to PyPI (https://pypi.org/manage/account/) or TestPyPI (https://test.pypi.org/manage/account/)
        pypi_token: ${{ secrets.PYPI_KEY }} # optional
        # Name of a repository where the package will be uploaded
        repository_name: inventree_digikey_integration # optional
